# Setup
title:        Welcome to GitHub page
tagline:      Tool for converting to DCAT and webinterface
baseurl:      "/webinterface-fedict"
paginate:     1

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com 


gems: [jekyll-paginate]

#Others
markdown: kramdown