# Setup
title:        Welcome to GitHub page
tagline:      Webinterface for browsing datasets
#baseurl:      ""
baseurl:      "/webinterface-fedict"

paginate:     1

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com 


gems: [jekyll-paginate]

#Others
markdown: kramdown