# Setup
title:        DCAT Web-interface
tagline:      Web-interface for browsing datasets
#baseurl:      ""
baseurl:      "/webinterface-fedict"

paginate:     1

# About/contact
author:
  name:       oSoc16
  url:        http://2016.summerofcode.be/


gems: [jekyll-paginate]

#Others
markdown: kramdown